on: ["push", "pull_request"]

name: Test

concurrency:
  # Cancel older, in-progress jobs from the same PR, same workflow.
  # use run_id if the job is triggered by a push to ensure
  # push-triggered jobs to not get canceled.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
              python-version: "3.10"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .[lint]

        - name: Run Black
          run: black --check .

        - name: Run isort
          run: isort --check-only .

        - name: Run flake8
          run: flake8 .

        - name: Run mdformat
          run: mdformat . --check

    type-check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
              python-version: "3.10"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .[lint,test]

        - name: Run MyPy
          run: mypy .

    functional:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]   # eventually add `windows-latest`
                python-version: [3.8, 3.9, "3.10", "3.11"]

        steps:
        - uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
              python-version: ${{ matrix.python-version }}

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .[test]

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
              node-version: '16'

        - name: Install Node Dependencies
          run: npm install --global ganache

        - name: Run Tests
          run: pytest -m "not fork and not manual and not fuzzing"
          env:
            # Needed in non-fork tests so that ape-ens works.
            WEB3_ETHEREUM_MAINNET_ALCHEMY_API_KEY: ${{ secrets.WEB3_ETHEREUM_MAINNET_ALCHEMY_API_KEY }}

        - name: Run Fork Tests (Alchemy)
          # Only run tests requiring Alchemy if not from a forked repo (Else it always fails)
          if: github.event.pull_request.head.repo.full_name == github.repository
          run: pytest -m fork
          env:
            # Used in fork tests as well as ape-ens.
            WEB3_ETHEREUM_MAINNET_ALCHEMY_API_KEY: ${{ secrets.WEB3_ETHEREUM_MAINNET_ALCHEMY_API_KEY }}
            WEB3_ETHEREUM_GOERLI_ALCHEMY_API_KEY: ${{ secrets.WEB3_ETHEREUM_GOERLI_ALCHEMY_API_KEY }}
            WEB3_POLYGON_MUMBAI_ALCHEMY_API_KEY: ${{ secrets.WEB3_POLYGON_MUMBAI_ALCHEMY_API_KEY }}

# NOTE: uncomment this block after you've marked tests with @pytest.mark.fuzzing
#    fuzzing:
#        runs-on: ubuntu-latest
#
#        strategy:
#            fail-fast: true
#
#        steps:
#        - uses: actions/checkout@v3
#
#        - name: Setup Python
#          uses: actions/setup-python@v4
#          with:
#              python-version: "3.10"
#
#        - name: Install Dependencies
#          run: pip install .[test]
#
#        - name: Run Tests
#          run: pytest -m "fuzzing" --no-cov -s
